name: "Add issues to 'KittyCode Project'"

on:
  issues:
    types: [opened]
jobs:
  createCard:
    runs-on: ubuntu-latest
    steps:
      - uses: KittyCAD/ts-actions/add-issues-to-project@v0.3.0
        with:
          token: ${{ secrets.GLOBAL_PAT }}
          issue-node: ${{ github.event.issue.node_id }}"
