[package]
name = "kittycad"
description = "A fully generated & opinionated API client for the KittyCAD API."
version = "0.2.3"
documentation = "https://docs.rs/kittycad"
readme = "README.md"
repository = "https://github.com/KittyCAD/kittycad.rs/tree/main/kittycad"
edition = "2018"
license = "MIT"

[dependencies]
anyhow = "1"
async-trait = "^0.1.53"
bytes = { version = "1", features = ["serde"] }
clap = { version = "^3.2.12", features = ["cargo", "derive", "env", "unicode"] }
chrono = { version = "0.4", default-features = false, features = ["serde"] }
data-encoding = "^2.3.2"
dirs = { version = "^4.0.0", optional = true }
format_serde_error = "^0.3.0"
futures = "0.3.26"
http = "^0.2.8"
itertools = "^0.10.5"
log = { version = "^0.4", features = ["serde"] }
mime = "0.3"
parse-display = "^0.5"
percent-encoding = "2.1"
phonenumber = "^0.3.1"
reqwest = { version = "0.11", default-features = false, features = ["json", "multipart", "rustls-tls"] }
reqwest-conditional-middleware = "0.1.0"
reqwest-middleware = "0.1.5"
reqwest-retry = "0.1.4"
reqwest-tracing = { version = "0.3.0", features = ["opentelemetry_0_17"] }
schemars = { version = "0.8", features = ["bytes", "chrono", "url", "uuid1"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_urlencoded = "^0.7"
tabled = { version = "0.8.0", features = ["color"] }
thiserror = "1"
tokio = { version = "1.20.1", features = ["full"] }
tracing = "^0.1"
url = { version = "2", features = ["serde"] }
uuid = { version = "1", features = ["serde", "v4"] }

[dev-dependencies]
expectorate = "1"
futures-util = "^0.3.26"
pretty_assertions = "1"
rand = "0.8"
tokio = { version = "1.20.0", features = ["full"] }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
