[package]
name = "kittycad"
description = "A fully generated & opinionated API client for the kittycad API."
version = "0.1.6"
documentation = "https://docs.rs/kittycad/"
repository = "https://github.com/Kittycad/kittycad.rs/tree/main/kittycad"
readme = "README.md"
edition = "2018"
license = "MIT"

[dependencies]
anyhow = "1"
async-trait = "^0.1.53"
bytes = { version = "1", features = ["serde"] }
clap = { version = "^3.2.12", features = ["cargo", "derive", "env", "unicode"] }
chrono = { version = "0.4", features = ["serde"] }
chrono-humanize = "^0.2.1"
data-encoding = "^2.3.2"
dirs = { version = "^4.0.0", optional = true }
http = "^0.2.8"
hyperx = "1"
log = { version = "^0.4", features = ["serde"] }
mime = "0.3"
parse-display = "^0.5"
percent-encoding = "2.1"
reqwest = { version = "0.11", default-features = false, features = ["json", "multipart", "rustls-tls"] }
schemars = { version = "0.8", features = ["bytes", "chrono", "url", "uuid1"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_with = "2"
serde_urlencoded = "^0.7"
tabled = { version = "0.7.0", features = ["color"] }
thiserror = "^1"
url = { version = "2", features = ["serde"] }
uuid = { version = "1", features = ["serde", "v4"] }

[dev-dependencies]
pretty_assertions = "1"
tokio = { version = "1.8.0", features = ["full"] }

[features]
# enable etag-based http_cache functionality
httpcache = ["dirs"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
