on:
  push:
    paths:
      - '**.rs'
      - Cargo.toml
      - Cargo.lock
      - .github/workflows/cargo-test.yml
name: cargo test
jobs:
  cargotest:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install latest stable/nightly
        shell: bash
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash -s -- -y
          rustup default nightly
          rustup default stable
          rustup component add rustfmt
          rustup component add rustfmt --toolchain nightly
          rustup component add clippy
          echo PATH="${HOME}/.cargo/bin:${PATH}" >> ${GITHUB_ENV}

      - uses: taiki-e/install-action@cargo-llvm-cov
      - uses: taiki-e/install-action@nextest

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.5.0

      - name: cargo test
        shell: bash
        run: |
          cargo llvm-cov nextest --all --exclude engine --lcov --output-path lcov.info --test-threads=1
        env:
          KITTYCAD_API_TOKEN: ${{secrets.KITTYCAD_API_TOKEN}}

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          fail_ci_if_error: true
          flags: unittests
          verbose: true
          files: lcov.info
