on:
  push:
    paths:
      - '**.rs'
      - Cargo.toml
      - Cargo.lock
      - .github/workflows/cargo-doc.yml
name: cargo doc
jobs:
  cargodoc:
    name: cargo doc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install latest rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
            components: rustfmt, clippy
      - name: Cache cargo registry
        uses: actions/cache@v3.0.6
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache cargo index
        uses: actions/cache@v3.0.6
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache cargo doc
        uses: actions/cache@v3.0.6
        with:
          path: target
          key: ${{ runner.os }}-cargo-doc-target-${{ hashFiles('**/Cargo.lock') }}
      - name: Run cargo doc
        run: |
          cargo doc --all
        shell: bash
